# TASK level variables
- name: variablw with task level
  hosts: localhost
  vars:
    course: "DevOps321"
    Trainer: "sivakumar"
    Duration: "110HRS"
  tasks:
  - name: check variables
    vars:
      course: "dev with aws"
    ansible.builtin.debug:
      msg: "hi, I am learning {{course}}, trainer is {{Trainer}}, Duration {{Duration}}"