- name: datatypes 
  hosts: localhosts
  tasks:
  vars:
    name: shiva
    skills:
    - DevOps
    - Shell
    - Ansible
    - Linux
    Experience:
      DevOps: 4
      AWS: 2
      Docker: 2
    Trainer: true
  tasks:
  - name: print key value pairs
    ansible.builtin.debug:
      msg: "name:{{name}}"
    
    - name: print list
      ansible.buitin.debug:
       msg: "skills:{{skills}}"

    - name: print map
      ansible.builtin.debug:
        msg: "Experience: {{Experience}}"

