- name: datatypes 
  hosts: localhosts
  vars:
    NAME: shiva
    Skills:
    - DevOps
    - Shell
    - Ansible
    - Linux
    Experience:
      DevOps: 4
      AWS: 2
      Docker: 2
    Trainer: true
  tasks:
  - name: print key value pairs
    ansible.builtin.debug:
      msg: "name:{{NAME}}"
    
  - name: print list
    ansible.buitin.debug:
      msg: "skills:{{Skills}}"

  - name: print map
    ansible.builtin.debug:
      msg: "Experience: {{Experience}}"

